"""add core models

Revision ID: dec226ca1253
Revises: 20260617_0001
Create Date: 2026-06-16 21:55:57.377625
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'dec226ca1253'
down_revision: str | None = '20260617_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('primary_author_name', sa.String(length=300), nullable=True),
    sa.Column('isbn10', sa.String(length=10), nullable=True),
    sa.Column('isbn13', sa.String(length=13), nullable=True),
    sa.Column('libby_title_id', sa.String(length=100), nullable=True),
    sa.Column('libby_share_url', sa.String(length=1000), nullable=True),
    sa.Column('publisher', sa.String(length=300), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('completed_on', sa.Date(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('audio_seconds', sa.Integer(), nullable=True),
    sa.Column('manual_progress_percent', sa.Float(), nullable=True),
    sa.Column('cover_url', sa.String(length=1000), nullable=True),
    sa.Column('cover_color', sa.String(length=20), nullable=True),
    sa.Column('title_source', sa.String(length=50), nullable=True),
    sa.Column('author_source', sa.String(length=50), nullable=True),
    sa.Column('metadata_source', sa.String(length=50), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_archived_at'), 'books', ['archived_at'], unique=False)
    op.create_index(op.f('ix_books_completed_on'), 'books', ['completed_on'], unique=False)
    op.create_index(op.f('ix_books_format'), 'books', ['format'], unique=False)
    op.create_index(op.f('ix_books_isbn10'), 'books', ['isbn10'], unique=False)
    op.create_index(op.f('ix_books_isbn13'), 'books', ['isbn13'], unique=False)
    op.create_index(op.f('ix_books_libby_title_id'), 'books', ['libby_title_id'], unique=False)
    op.create_index(op.f('ix_books_primary_author_name'), 'books', ['primary_author_name'], unique=False)
    op.create_index(op.f('ix_books_status'), 'books', ['status'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_index(op.f('ix_books_user_id'), 'books', ['user_id'], unique=False)
    op.create_table('book_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('position_seconds', sa.Integer(), nullable=True),
    sa.Column('position_pages', sa.Integer(), nullable=True),
    sa.Column('total_seconds', sa.Integer(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('last_borrowed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scraped_borrowed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_inferred', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', name='uq_book_progress_book_id')
    )
    op.create_index(op.f('ix_book_progress_book_id'), 'book_progress', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_progress_status_inferred'), 'book_progress', ['status_inferred'], unique=False)
    op.create_index(op.f('ix_book_progress_user_id'), 'book_progress', ['user_id'], unique=False)
    op.create_table('reading_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_event_id', sa.String(length=300), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'source_event_id', name='uq_reading_events_source_event')
    )
    op.create_index(op.f('ix_reading_events_book_id'), 'reading_events', ['book_id'], unique=False)
    op.create_index(op.f('ix_reading_events_event_date'), 'reading_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_reading_events_event_type'), 'reading_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_reading_events_source'), 'reading_events', ['source'], unique=False)
    op.create_index(op.f('ix_reading_events_source_event_id'), 'reading_events', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_reading_events_user_id'), 'reading_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reading_events_user_id'), table_name='reading_events')
    op.drop_index(op.f('ix_reading_events_source_event_id'), table_name='reading_events')
    op.drop_index(op.f('ix_reading_events_source'), table_name='reading_events')
    op.drop_index(op.f('ix_reading_events_event_type'), table_name='reading_events')
    op.drop_index(op.f('ix_reading_events_event_date'), table_name='reading_events')
    op.drop_index(op.f('ix_reading_events_book_id'), table_name='reading_events')
    op.drop_table('reading_events')
    op.drop_index(op.f('ix_book_progress_user_id'), table_name='book_progress')
    op.drop_index(op.f('ix_book_progress_status_inferred'), table_name='book_progress')
    op.drop_index(op.f('ix_book_progress_book_id'), table_name='book_progress')
    op.drop_table('book_progress')
    op.drop_index(op.f('ix_books_user_id'), table_name='books')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_status'), table_name='books')
    op.drop_index(op.f('ix_books_primary_author_name'), table_name='books')
    op.drop_index(op.f('ix_books_libby_title_id'), table_name='books')
    op.drop_index(op.f('ix_books_isbn13'), table_name='books')
    op.drop_index(op.f('ix_books_isbn10'), table_name='books')
    op.drop_index(op.f('ix_books_format'), table_name='books')
    op.drop_index(op.f('ix_books_completed_on'), table_name='books')
    op.drop_index(op.f('ix_books_archived_at'), table_name='books')
    op.drop_table('books')
    op.drop_table('users')
    # ### end Alembic commands ###
